export function buildHelpText(cliVersion: string) {
  return [
    `vernclaw-cli v${cliVersion}`,
    '',
    'Usage: vernclaw-cli <command> [options]',
    '',
    'Commands:',
    '  login                    Authenticate via browser or API key',
    '  logout                   Remove stored credentials',
    '  list                     List available connectors',
    '  describe <connector>     Show connector details and parameters',
    '  invoke <connector>       Run a connector and print JSON output',
    '  job get <jobId>          Check status of an async job',
    '  status                   Display current login, subscription, and credit status',
    '',
    'Options:',
    '  --help                   Show this help message',
    '  --pretty                 Print human-readable Markdown instead of JSON',
    '  --api-key <key>          Use a specific API key',
    '  --api-base-url <url>     Override the API base URL',
    '',
    'Examples:',
    '  vernclaw-cli login',
    '  vernclaw-cli login --api-key YOUR_API_KEY',
    '  vernclaw-cli status',
    '  vernclaw-cli list',
    '  vernclaw-cli describe seo.website-traffic',
    '  vernclaw-cli invoke seo.website-traffic --domain example.com',
    '',
    'Tip: `vernclaw-cli describe <connector>` shows required flags and an example invoke command.',
    '',
    'Docs: https://vernclaw.com/docs/connectors/cli',
    '',
  ].join('\n');
}
